"""Update the phone to not unige

Revision ID: 08c8686d1def
Revises: a47a91a32bc1
Create Date: 2024-09-28 10:54:07.103560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c8686d1def'
down_revision = 'a47a91a32bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index('phone_number')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('phone_number', ['phone_number'], unique=True)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index('phone_number', ['phone_number'], unique=True)

    # ### end Alembic commands ###
