"""Update the user tabel to use JWT

Revision ID: 3cd4c52fd09a
Revises: c97275af74c1
Create Date: 2024-08-22 10:51:05.496245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd4c52fd09a'
down_revision = 'c97275af74c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activation_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_token', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
